### ISSUE TITLE
`residues_` as `std::vector` instead of `unordered_map` in PDB format

### ISSUE THREAD

**Issue by pgbarletta** [chemfiles/chemfiles#113]
Currently, when iterating over residues they come out unordered even though they are always ordered on the input file. I think this holds true for any format. This must be due to the type of the `residue_` variable, `unordered_map`,  in the `PDB` format class.  When the info is passed onto the `residue_` variable of the `Topology` class, we end up with an unordered vector.
Since data is already ordered, I think a `std::vector`  would be more appropriate.

**Comment by Luthaf** [comment]
We still need a map, because residues id are not guaranteed to be in order in the input. So while building the residue list, we need to lookup the residue with its id in the file, and we can not just index into a vector.

Changing the unordered map for a ordered `std::map<size_t, residue>` could be a solution, but this would mean that the Residues are sorted by resid instead of the order of apparition in the file.

We could also keep the residues in the order in which the are in the file by having two members: a `std::vector<Residue>` and a `std::unordered_map<size_t, size_t>` mapping residues id to the index in the `std::vector`.

Please let me know if I am unclear, this feels a bit confuse to me.

**Comment by pgbarletta** [comment]
Mmm..., this may be another chemistry/biology argument. Have you found PDB files with unordered residues? I mean, unordered according to their `resSeq`  numbers?

**Comment by Luthaf** [comment]
> Mmm..., this may be another chemistry/biology argument.

Maybe yes =)

I never found one, but I don't see why they could not exist. If all valid (from the PDB repository point of view) files have residues in order, then just changing the `std::unordered_map` to a `std::map` should be enough to get them in order in the topology.

**Comment by pgbarletta** [comment]
Yes, I understand there is a little overhead with `std::map` that orders its elements each time a new element is inserted. 
If we use `std::vector` and just `push_back()` each new residue, we would assume they were ordered and it could  also be useful to preserve the original residue ordering in the rare case they weren't ordered according to `resSeq` and the user wanted it so.

Anyway, your call, I'm just happy if I don't have to sort the residues after reading.

**Comment by Luthaf** [comment]
> If we use std::vector and just push_back() each new residue, we would assume they were ordered and it could also be useful to preserve the original residue ordering in the rare case they weren't ordered according to resSeq and the user wanted it so.

The main problem with this is if we have a file like this:

```
CRYST1 15.000 15.000 15.000 90.00 90.00 90.00
ATOM      1  O       X   3       0.417   8.303  11.737  0.00  0.00
ATOM      2  H       X   3       1.320   8.480  12.003  0.00  0.00
ATOM      3  H       X   3       0.332   8.726  10.882  0.00  0.00
ATOM      4  O       X   1       9.733   8.950   5.501  0.00  0.00
ATOM      5  H       X   1      10.058   9.331   6.317  0.00  0.00
ATOM      6  H       X   2       8.922   9.426   5.320  0.00  0.00
ATOM      7  O       X   2       1.497   5.859   1.682  0.00  0.00
END
```

We read the first line and push a new residue to the vector. Then we read the second line, and we now have an issue: how do we know that the residue we just pushed was the residue with resSeq 3?  With a vector, we need to search for all residues in the vector to know where to add our atom. With a map, we can directly get the right residue.

**Comment by pgbarletta** [comment]
Ah, right. I was thinking of doing binary search, but that would only do if the residues were ordered.
