### ISSUE TITLE
Can't write PDBs with more than 100000 atoms

### ISSUE THREAD

**Issue by kain88-de** [chemfiles/chemfiles#132]
See https://github.com/chemfiles/chemfiles/blob/f7e4f7ee59ed7a9eebaa1ba6f79932cf8d5f10b4/src/formats/PDB.cpp#L318

The usual way to handle this is to start counting from 1 again. Similar to an integer overflow. MDAnalysis writes PDB's with that behavior and reads them accordingly.

**Comment by Luthaf** [comment]
Just to clarify, the code can and will write PDB with more than 100000 atoms, but will replace the atomic id by `'*****'` for all atoms after the 99999.

I am not sure what is the best behaviour here. Starting again at 1 might confuse other readers that do use the atomic index, as they are no longer unique. At the same time, using '****' is invalid according to the standard (but the standard does not specify what happens with more than 100000 atoms), and might also confuse other readers.

The current behaviour was picked to follow VMD: https://github.com/chemfiles/molfiles/blob/a029c1f1548e7a969eae53420d045f55b0985c3a/src/readpdb.h#L360-L373

**Comment by kain88-de** [comment]
Oh, I wasn't aware that VMD does this. Most other tools I come across so far that handle such large PDB's just restart the counter (or fail outright).  But it appears that MDAnalysis can also read the `*****` lines.  Having inconsistent extensions to a standard is a joy.
