### ISSUE TITLE
Residue connectivy not reflected in topology

### ISSUE THREAD

**Issue by frodofine** [chemfiles/chemfiles#144]
The connectivity of residues to one another (for example the peptide bond between two amino acids in a protein) is not assigned for valid PDBs. Currently, bonds are assigned based on a distance criterion which may disrupt ligand connectivity (especially with metals). Information in some crystallographic file formats, such as CIF, provide this information by specifying a bond type (like  'L-PEPTIDE LINKING' for a protein).

One solution for assignment of residue connectivity is to leverage this information, along with the atom name, to assign interresidue bonds. For example, the atom name 'C' is always bond to atom name 'N' in a protein PDB. Implementing this should not be difficult, assuming it is desirable.

**Comment by Luthaf** [comment]
I am not sure I completely understand the issue here. Bonds are only assigned using a distance criterion if [`Frame::guess_topology`](https://github.com/chemfiles/chemfiles/blob/b01be9443d16294646684d463f618bf5b52bc360/include/chemfiles/Frame.hpp#L227-L235) is called. Else we use whatever is in the file.

Specifically for PDB, we use the [`CONNECT`](https://github.com/chemfiles/chemfiles/blob/b01be9443d16294646684d463f618bf5b52bc360/src/formats/PDB.cpp#L210) records in the file. So if the file is missing CONNECT records, then the topology will not contain a bond.

At the same time, this reminds me that the [standard](https://www.wwpdb.org/documentation/file-format-content/format33/sect10.html) talk about the "standard residue connectivity table", but I could not find any definition of this table. From what you say, does this means that if the residue name is one of the amino-acid, then we should add an implicit bond between two consecutive residues ? Or is there any other kind of standard connectivity table ? I don't know much about PDB (I am not working with proteins at all), this is why I don't really know what all this is about.

**Comment by frodofine** [comment]
It's more of a suggestion/feature request than an actual issue. A potential issue I've seen with some distance based bond determination schemes is that they may interpret the bonds in a ligand incorrectly, especially if that ligand is near a metal atom. [Frame::guess_bonds](https://github.com/chemfiles/chemfiles/blob/b01be9443d16294646684d463f618bf5b52bc360/src/Frame.cpp#L49) throws out all bonds when it runs.

PDBs do not have CONECT records for standard atoms. In other words, if an atom is defined with the [ATOM record](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM), its connectivity is not explicitly stated (see the second paragraph under overview). HETATM records are required to have this information, however.

Yes there is a standard, and it is available here: ftp://ftp.wwpdb.org/pub/pdb/data/monomers/ (FTP don't work well here), but it is defined for all possible hetero complexes - not just standard amino/nucleic acids.  This standard nomenclature can be viewed visually on RCSB ( for example, [glutamate](http://www.rcsb.org/ligand/GLU) - be sure to show the labels).

What I am suggesting is implementing this standard connectivity during PDB parsing for amino and nucleic acids so that one does not need to run [Frame::guess_bonds](https://github.com/chemfiles/chemfiles/blob/b01be9443d16294646684d463f618bf5b52bc360/src/Frame.cpp#L49) to obtain a sane starting topology. Again, this is more of a suggestion than an issue and I'd be happy to implement this myself if it is desired.

**Comment by Luthaf** [comment]
OK, thank you for the explanation. I definitively agree with implementing this part of the standard, as long as it does not interfere with non-standard PDB too much.

Looking at files in the FTP directory, they look like this:

```
RESIDUE   GLU     19
CONECT      N      3 CA   H    H2  
CONECT      CA     4 N    C    CB   HA  
CONECT      C      3 CA   O    OXT 
CONECT      O      1 C   
CONECT      CB     4 CA   CG   HB2  HB3 
CONECT      CG     4 CB   CD   HG2  HG3 
CONECT      CD     3 CG   OE1  OE2 
CONECT      OE1    1 CD  
CONECT      OE2    2 CD   HE2 
CONECT      OXT    2 C    HXT 
CONECT      H      1 N   
CONECT      H2     1 N   
CONECT      HA     1 CA  
CONECT      HB2    1 CB  
CONECT      HB3    1 CB  
CONECT      HG2    1 CG  
CONECT      HG3    1 CG  
CONECT      HE2    1 OE2 
CONECT      HXT    1 OXT 
END   
HET    GLU             19
HETNAM     GLU GLUTAMIC ACID
FORMUL      GLU    C5 H9 N1 O4
```

Combining this and what you said, I think we could add bonds between `ATOM` records, if the residue name match one of the names in the standard tables; adding the bonds if and only if the atomic names matches. We would also need to add bonds between consecutive residues, right ?

I'll be happy if you can implement this =) I think the hardest part will be using the data from the PDB monomers. The whole list of monomers is available here: http://ftp.wwpdb.org/pub/pdb/data/monomers/het_dictionary.txt. We might want to convert the file into some kind of data we can use inside the PDBFormat class.

**Comment by frodofine** [comment]
I think the best way to approach this is to convert the table to a C++ map using a Perl or Python script. The C++ file will contain a Map of Maps (a Perl concept, but it works here) that maps the residue name (the HET line) to a second map that in turn maps the atom name to its connections. The PDB class will need to be modified so that after a residue is parsed, this map is used to make connections.

**Comment by Luthaf** [comment]
Sounds good :+1: 

I would rather use Python for this, as it is already used for this kind of scripts in chemfiles (see the elements.py file)

**Comment by frodofine** [comment]
I'll post code to a new branch later this evening (my time), but I want to discuss something first.

Using the entire lookup table yields a C++ map so large it crashes GCC and Clang (but small subsets of the table do not)! So I propose that we only support the amino acids / nucleic acids found in the major forcefields. This typically means the standard 20 natural L-amino acids, A, U, G, and C along with their deoxy counterparts (plus T), and common membrane lipids. For reference, see the [amber forcefield](https://github.com/pandegroup/openmm/tree/master/wrappers/python/simtk/openmm/app/data/amber14).

The script can produce any subset of the table, so users skilled enough to compile Chemfiles can produce their own include files that pertain to their needs, but we will only ship the residues mentioned above as the majority of people running protein dynamics will be satisfied. Plus, heteroatoms/residues are often explicitly bonded with `CONECT` records, so having them in the look-up table will be redundant anyway.

**Comment by Luthaf** [comment]
> Using the entire lookup table yields a C++ map so large it crashes GCC and Clang (but small subsets of the table do not)!

Whoops ... Just out of curiosity, how big is the file ?

I am fine with only shipping amino-acids and nucleic acids. I think we could win a bit of memory by using smarter data structures/string interners, but this can be done later if there is demand for it.

**Comment by frodofine** [comment]
About 40MB, but I don't know of any software that would attempt anything that is not an amino/nucleic acid for a `PDB` structure.

**Comment by Luthaf** [comment]
Yeah, we can leave full PDB validation to the actual PDB database :smiley:

**Comment by frodofine** [comment]
Well that's a whole 'nother can o' worms :grin:
