### ISSUE TITLE
Rewrite molfile plugins

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#154]
The [`Molfile`](https://github.com/chemfiles/chemfiles/blob/2ecb0d2f5db6270e7d88462e68c6bf24b8d9ed37/include/chemfiles/formats/Molfile.hpp#L34) readers have several issues:

- no support for read_step (see #153 for a workaround)
- no write support
- writing to stdout/stderr instead of using chemfiles::warning
- the code is rather hard to read and modify

I think it can be worth it to rewrite the corresponding formats directly in chemfiles

**Binary formats**

- [x] GROMACS .trr #265 #275
- [x] GROMACS .xtc #262 #274 
- [ ] LAMMPS/NAMD .dcd

There is a C library for reading xtc and trr files: http://www.gromacs.org/Developer_Zone/Programming_Guide/XTC_Library. Version 1.1.4 is BSD licensed.

For DCD and GRO files, the code from molfiles is BSD licensed and could be adapted and improved.

**Text formats**

- [x] GROMACS .gro
- [ ] LAMMPS trajectory
- [x] MOL2 files
- [ ] Molden files

**Comment by frodofine** [comment]
I can take care of the MOL2 support, I've written a parser/writer for this format in the past.

**Comment by marvinbernhardt** [comment]
This would be super cool. Especially since at the moment chemfiles does not read velocities from .trr files, which for me was the criterion not to use it.

**Comment by marvinbernhardt** [comment]
There is https://github.com/wesbarnett/libxdrfile, but it is gpl, so i guess it can not be used

**Comment by Luthaf** [comment]
Yes, as I was saying in gitter, GPL version of the library are out =/.

The version provided by GROMACS (http://www.gromacs.org/Developer_Zone/Programming_Guide/XTC_Library) is BSD though (the website says LGPL, but the COPYING file says is 2-clauses BSD). It is not available on github, but this is not really an issue =)

**Comment by Luthaf** [comment]
> This would be super cool. Especially since at the moment chemfiles does not read velocities from .trr files, which for me was the criterion not to use it.

@marvinbernhardt The code to read TRR file, including velocity, has just been added by @ezavod, if that is still of interest to you!

**Comment by marvinbernhardt** [comment]
It is! And It works for me, thanks for the implementation.

**Comment by Luthaf** [comment]
Closing in favor of separate issues for each format
