### ISSUE TITLE
Support Storing Bond Orders

### ISSUE THREAD

**Issue by frodofine** [chemfiles/chemfiles#170]
Many formats store the bond order of various bonds in molecules. Examples include MOL2, SMI, MMTF, and SDF.  Currently Chemfiles not store bond orders, which makes writing these formats properly not impossible.

My solution is to store the bond order as an integer in the bond class.  Some complications include the fact some formats include orders such as 'ar' for an aromatic bond and 'am' for amide bonds. We could make an enum for storing this, but I'd like to hear other suggestions as well.

**Comment by Luthaf** [comment]
I think an enumeration would be nice, what would be the cases? `SINGLE`, `DOUBLE`, `TRIPLE`, `AROMATIC`, and `AMIDE`? Maybe `UNKNOWN` too ?

From the C API point of view, I like the fact that one can get bonds in an array of integers, so maybe having a separate function to get bond order ? Either bond order for all bonds, or bond order for a given bond:

```c
enum chfl_bond_orders {
    CHFL_BOND_SINGLE = 1,
    // ...
}

chfl_status chfl_topology_get_bond_orders(const CHFL_TOPOLOGY* const topology, chfl_bond_orders orders[], uint64_t count);

chfl_status chfl_topology_get_bond_order(const CHFL_TOPOLOGY* const topology, uint64_t i, uint64_t j, chfl_bond_orders* order);
```

**Comment by frodofine** [comment]
I've seen up to quintuplet bonds in the CSD (but at that point, what's really a bond from a theoretical perspective?). The ones you listed are good, but I think `UNKNOWN` should be zero.

Maybe the addition of a conjugated bond (IE: butadiene)? I think this might a bit much as formats do not list conjugated bonds, but it is worth mentioning.

**Comment by Luthaf** [comment]
How about defining the bond enum to something like this:

```cpp
enum BondOrder {
    UNKNOWN = 0,
    SINGLE = 1,
    DOUBLE = 2,
    TRIPLE = 3,
    QUADRUPLE = 4,
    QINTUPLET = 5,

    // space for more bond types if needed
    AMIDE = 254,
    AROMATIC = 255,
}
```

> Maybe the addition of a conjugated bond (IE: butadiene)? I think this might a bit much as formats do not list conjugated bonds, but it is worth mentioning.

I would rather not put it in if no format use it. We can always add it later if needed.

**Comment by frodofine** [comment]
Sounds good! I think I did something like this when I was working on SMI support, I'll probably modify that and make a PR that supports Bond Orders for formats already implemented.
