### ISSUE TITLE
Improve handling of ATOM/HETATM in PDB and mmCIF

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#210]
Launched here: https://github.com/chemfiles/chemfiles/pull/197#discussion_r217929224

Right now, PDB uses HETATM as the default as I could not find a way to differentiate between ATOM/HETATM records. mmCIF uses ATOM as the default, so we might want to unify them and use the same default (I would argue for HETATM, but I could live with ATOM too).

In the longer run, we might want to follow the actual rules for this and try to find atoms in the PDB connectivity table. The only downsides I could see for this are (1) a bit of cost looking up each atom and (2) we don't include the full connectivity tables in chemfiles yet.

**Comment by frodofine** [comment]
Actually, the distinction between `HETATM` and `ATOM` in `PDB` files is a bit more straightforward.  Everything is `HETATM` unless it is a specific residue linkage type, which are predefined.  Therefore, we only need to check the residue type and not worry about connectivity tables.

**Comment by frodofine** [comment]
I wondering if it would be better to remain the property something like `is_standard` and reverse its meaning.

**Comment by frodofine** [comment]
`is_standard_pdb` is probably best as it is assigned by the wwPDB, not RCSB.  Also, it should be a `Residue` property as it assigned based on connectivity, not on atoms. This means we only need to make the check per residue, not per atom.  We already have all the standard residues in the connectivity table, so one can just check there if need be.

**Comment by Luthaf** [comment]
Sounds good to me !
