### ISSUE TITLE
Release 0.9 planning

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#214]
So I just created the release-0.9 branch (https://github.com/chemfiles/chemfiles/tree/release-0.9), and tagged [0.9.0-rc1](https://github.com/chemfiles/chemfiles/releases/tag/0.9.0-rc1). 

Here are the remaining work to do for an official 0.9 release:

- [x] Update bindings to work with 0.9
  * [x] Fortran
  * [x] Rust
  * [x] Julia
  * [x] Python
- [x] Update packages
  * [x] [OpenSuse Build Services](https://build.opensuse.org/package/show/home:Luthaf/chemfiles)
  * [x] Conda-forge
       - [x] [chemfiles-lib](https://github.com/conda-forge/chemfiles-lib-feedstock) (https://github.com/conda-forge/chemfiles-lib-feedstock/pull/20)
       - [x] [chemfiles-python](https://github.com/conda-forge/chemfiles-python-feedstock)
- [x] Write a blog post announcing the release
- [x] Check that documentation is online for 0.9
  * [x] C/C++
  * [x] Fortran
  * [x] Rust
  * [x] Julia
  * [x] Python

There are also a few instructions in the [wiki](https://github.com/chemfiles/chemfiles/wiki/Release-process). 

Please tell here if you can help for any of these items!

**Comment by Luthaf** [comment]
I already started to work on updating Rust and Fortran bindings, as well as [bindgen](https://github.com/chemfiles/bindgen).

**Comment by frodofine** [comment]
I'll take a look at Julia, but I recently updated this so I'm not too concerned.

I'm thinking C# as well, but maybe that's not needed for 0.9!

**Comment by Luthaf** [comment]
So there seems to be an error with Windows & the extern templates in the new `property_map::get` API (see https://github.com/conda-forge/chemfiles-lib-feedstock/pull/20). I'll try to see what is going on and why this was not caught by CI.

> I'm thinking C# as well, but maybe that's not needed for 0.9!

That would be a very nice addition, but yes, it can come later! Mind to open an issue to discuss it?

**Comment by frodofine** [comment]
I will, but I think `bindgen` is the place!

**Comment by Luthaf** [comment]
Done, and all finished! http://luthaf.fr/announcing-chemfiles-0.9.html

Many thanks again @frodofine for all your help =)

**Comment by frodofine** [comment]
Glad to help! I really need to get back to those PRs I submitted, just got bogged down with other projects...
