### ISSUE TITLE
Updated homebrew bottle

### ISSUE THREAD

**Issue by staticfloat** [chemfiles/chemfiles#22]
Hello @Luthaf, I'm currently [going through my homebrew-juliadeps](https://github.com/staticfloat/homebrew-juliadeps/issues/84) tap, updating versions of software where appropriate, and wanted to check with you to see if upgrading to v0.4.0 of chemharp would be appropriate for the julia code that uses it.  Is that something I should do now, or should I wait until changes have been made on the julia side?

**Comment by Luthaf** [comment]
Actually, the 0.4 version of the Julia code is no longer using Homebrew for binary dependencies. Now that the 0.4 version has been released I think we can remove this formula from the juliadeps tap. Or keep it at 0.3, as they still may be some people using it (I do not think so, but let's dream!)

Having an "official" hombrew bottle will be nice, but is more something for 1.0.

**Comment by staticfloat** [comment]
Alright, I'll just leave it "as-is" for now, and wait for 1.0 to arrive. :)
-E
