### ISSUE TITLE
website - dead links

### ISSUE THREAD

**Issue by maxlevesque** [chemfiles/chemfiles#24]
Hi there,

In the main webpage of chemfiles, in section `Multiple languages` some links are not present or not valid.
See for instance Fortran :  
http://github.com/chemfiles/chemfiles.f90
instead of 
http://github.com/chemfiles/chemfiles.f03

See also links related to C++ and C.

**Comment by Luthaf** [comment]
Ooops ... Thank you for this one!

Fixed in https://github.com/chemfiles/chemfiles.github.io/commit/721b9b7fddfedb2ede6c5f0e102ef1d824afae47

> See also links related to C++ and C.

C and C++ sources are in the same repository, the main one.
