### ISSUE TITLE
feature request: Supporting SMILES format

### ISSUE THREAD

**Issue by KaneGreen** [chemfiles/chemfiles#241]
`SMILES` is an easy-to-use format for chemical structure input. I think it should be supported.
[`SMILES` on Wikipedia](https://en.wikipedia.org/wiki/Simplified_molecular-input_line-entry_system)
[OpenSMILES specification](http://opensmiles.org/opensmiles.html)
[SMILES tokens](http://www.dalkescientific.com/writings/diary/archive/2004/01/05/tokens.html)
[Daylight SMILES](http://www.daylight.com/smiles/)

**Comment by Luthaf** [comment]
Hi ! Thanks for opening this discussion.

SMILES looks like a nice format to support. As far as I know, it does not store coordinates, only the molecules topology, right? 

Also, hydrogen are not always explicitly defined, relying instead on the valence of standard atoms?

Implementation-wise, the OpenSMILES standard looks well defined and easy to parse. The interpretation of the parsed string and the construction of the molecule graph might be harder though. Do you know if there is any C or C++ library that we could use to parse SMILES ?

**Comment by KaneGreen** [comment]
Yes. SMILES stores topology only.
Converting topology to coordinates is hard because of energy minimization stuff. So some chemistry user use [Open Babel](https://openbabel.org/wiki/Main_Page) to do this.
However, converting coordinates to topology may be easier.

So, if topology to coordinates is hard, supporting SMILES as an output format is the reasonable first step.

Also I think SMILES format also helps InChI format (#188).

---------------
Sorry for that I don't know that C or C++ library to parse SMILES.
But I know one written in Rust that could. However, it has not been updated for a long time.
[acetylene-parser](https://gitlab.com/acetylene/acetylene-parser)

**Comment by frodofine** [comment]
I have some SMILES parsing code from another project that I can move upstream once I get the chance.

This will not help the InChI implementation as this is done through a separate library.
