### ISSUE TITLE
Reading XYZ file crashes from Python

### ISSUE THREAD

**Issue by richardjgowers** [chemfiles/chemfiles#257]
Is there a different repo for Python issues? 

I'm using 0.9.1 of chemfiles from conda-forge on an osx machine and this happens:

```python
In [1]: import chemfiles

In [2]: chemfiles.Trajectory('water.xyz', 'r', 'XYZ')
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument
Abort trap: 6
```

where `water.xyz` is 
```
3
water
H            9.625597       6.787278      12.673000
H            9.625597       8.420323      12.673000
O           10.203012       7.603800      12.673000
```

**Comment by Luthaf** [comment]
> Is there a different repo for Python issues?

There is https://github.com/chemfiles/chemfiles.py, but this seems to come from C++ side.

This error looks a lot like C++ ABI issue we already had: when compiling chemfiles with a given C++ standard lib and then running it with another, try/catch does not work since the typeid of exception changes =/

But I have never seen this on osx, only on Linux with the GCC 5 new C++11 ABI. What version of macOS are you using?

**Comment by richardjgowers** [comment]
@Luthaf I think it's the most recent, 10.14.5.  Tbh I think conda(-forge) is meant to build to prevent these sorts of things, maybe it's a recipe issue?

```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by Luthaf** [comment]
Ok, that's weird ... I am also on macOS 10.14.5, and I can't reproduce this crash =/

What would be the output of `otool -L <CONDA_PREFIX>/lib/libchemfiles.0.9.1.dylib`?

And if you can get a backtrace of the crash with lldb for example that could help.

**Comment by Luthaf** [comment]
On my machine, `conda list` gives `libcxx` and `libcxxabi` version at 8.0.0, build 4. Do you have the same?

**Comment by richardjgowers** [comment]
@Luthaf yeah maybe that's the difference:
```
# packages in environment at /Users/richardgowers/miniconda3/envs/mda:
#
# Name                    Version                   Build  Channel
libcblas                  3.8.0                4_openblas    conda-forge
libcurl                   7.62.0               h051b688_0
libcxx                    4.0.1                h579ed51_0
libcxxabi                 4.0.1                hebd6815_0
```

**Comment by Luthaf** [comment]
Do you have conda-forge first in `~/.condarc`? that could be the origin of the issue

**Comment by richardjgowers** [comment]
@Luthaf 

```channels:
  - conda-forge
  - defaults
channel_priority: flexible
```

from a quick look at the conda recipes, it might be that you need the cxx in the run requirements too?

**Comment by Luthaf** [comment]
Maybe, I'll have a look!

**Comment by Luthaf** [comment]
Let's move the issue over to https://github.com/conda-forge/chemfiles-lib-feedstock/issues/27
