### ISSUE TITLE
Do not allow reading trajectories in append mode

### ISSUE THREAD

**Issue by ezavod** [chemfiles/chemfiles#272]
It is currently [possible to read in append](https://github.com/chemfiles/chemfiles/blob/e13319b23ff86a5f949875dd5d66ccacf609b999/src/Trajectory.cpp#L137) mode.
IMHO this is not good:
- In C appending allows writing only (see [7.21.5.3  The `fopen` function](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf))
- When implementing writing/appending for some formats (I will hopefully have time to tackle XTC+TRR in a while) the underlying library (e.g. xdrfile) does not support reading while appending in most cases. So one would have to rewrite/do ugly workarounds to allow sthis anyways :(

Any thoughts on this?

Could do a PR that forbids this, it doesn't seem to break any tests :D

**Comment by Luthaf** [comment]
I have been thinking a bit about the append mode recently, and I would tend to agree with you on only having write capacities while in append mode. This would make everything simpler.

> Could do a PR that forbids this, it doesn't seem to break any tests :D

Yeah, appending is severly undertested =(
