### ISSUE TITLE
Segfault on macOS + clang when reading 1HTQ.pdb

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#328]
To reproduce, start by downloading the 1HTQ structure, in PDB format from https://www.rcsb.org/structure/1htq

Reading the file leads to a segfault on macOS + clang (potentially other platforms too, I did not try). From the debugger, the issue happen when rehashing and updating the property map on the residues in https://github.com/chemfiles/chemfiles/blob/6c44422ae07debd8a96ad287ebc8375ce058b6bd/src/formats/PDB.cpp#L458

A possible culprit would be move/copy constructor of Property with string values. Pinging @frodofine (congrats on your PhD!) in case you have an idea what is going on here.

**Comment by frodofine** [comment]
Hmm, I'll look into. I don't have access to a Mac because I cannot go onto campus, but I will try and reproduce the error on Windows or Linux.

Thanks!

**Comment by Luthaf** [comment]
If I find the motivation, I'll try to look a bit deeper into this. I wanted to fill an issue to not forget about it =)

**Comment by Luthaf** [comment]
Fixed by #329
