### ISSUE TITLE
Read helix handedness in PDB format

### ISSUE THREAD

**Issue by sguionni** [chemfiles/chemfiles#330]
I'm looking for a way to read helix handedness in PDB format.
I see left and right are merged into secondary_structure property, what to you think about splitting into "left alpha helix" and "right alpha helix"? Not sure if this is the best solution, maybe passing the helix type number into a new property could be more flexible for the user.

**Comment by Luthaf** [comment]
I don't see any issue with making more data accessible to the user. @frodofine, does this seems sensible to you?

**Comment by frodofine** [comment]
Sounds good to me, it's a string property so this should be easy.

**Comment by Luthaf** [comment]
@sguionni do you have an example of a file containing left-handed helix? I can not find any on the PDB archive

**Comment by sguionni** [comment]
@Luthaf yes: 1ptm, chain A, residus 211-216.
You can find more in this paper: https://www.sciencedirect.com/science/article/abs/pii/S0022283605000707?via%3Dihub (table 1)

**Comment by Luthaf** [comment]
The helix do not seems to be saved as left-handed in the PDB file: https://files.rcsb.org/view/1PTM.pdb. If I'm not mistaken, the corresponding line is 

```
HELIX    9   9 ASN A  209  HIS A  217  5                                   9    
```

with an helix code of 5 meaning `Right-handed 3 - 10`

In the paper, it looks like they re-did the helix assignment manually, and did not use the `HELIX` records from the files. I'll look at the other files to double check.

**Comment by Luthaf** [comment]
1NPC seems to have a left handed helix record in the PDB file, so I'll use it as a test case!

**Comment by sguionni** [comment]
Ok cool! I gave you infos from my colleagues, i'm personnally not an expert of files.
