### ISSUE TITLE
Expose Residue properties to selections

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#331]
From @mdimura  on gitter:

> How do I properly specify a property in a selection string? I tried "[chainname] A", but it gives an empty selection. Sorry, could not find an example in the docs.

The issue here is that `chainname` is a residue property, and only atomic properties are checked when evaluating selection: https://github.com/chemfiles/chemfiles/blob/49442411ab9c31680e03918b151ac3fa26c1958b/src/selections/expr.cpp#L323-L338

I think the best way to solve this is to give the same semantics as `resname` selections: if no property is found on the atom, check if the current atom is part of a residue, and if the residue contains the property.

Any thoughts?

**Comment by mdimura** [comment]
As a temporary workaround this patch worked for me:
```
diff --git a/src/selections/expr.cpp b/src/selections/expr.cpp
index bf7f1bb0..2b91f04f 100644
--- a/src/selections/expr.cpp
+++ b/src/selections/expr.cpp
@@ -332,6 +332,13 @@ const std::string& StringProperty::value(const Frame& frame, size_t i) const {
             );
         }
     } else {
+        auto residue = frame.topology().residue_for_atom(i);
+        if (residue) {
+            const auto& resProperty = residue->get(property_);
+            if (resProperty->kind() == Property::STRING) {
+                return resProperty->as_string();
+            }
+        }
         // No property with the given name
         return EMPTY_STRING;
     }

```

**Comment by Luthaf** [comment]
That is around 1/3rd of the PR required to implement this! (the other thirds being the same thing for boolean and numeric properties). 

Would you like to create a PR for this?

**Comment by mdimura** [comment]
Sure, will do.

**Comment by mdimura** [comment]
The tests and exceptions are in now!
