### ISSUE TITLE
#undef INFINITE not working on Windows

### ISSUE THREAD

**Issue by sguionni** [chemfiles/chemfiles#333]
I need to #undef by myself because this line seems to not be called: [link](https://github.com/chemfiles/chemfiles/blob/99486730d4849656308516c6f7ed60b74fd575bc/include/chemfiles/UnitCell.hpp#L10)

**Comment by Luthaf** [comment]
We will need more information here. Which compiler are you using, which version of the compiler, and how do you build chemfiles?

If you add a `message(STATUS "here")` after this line in the root CMakeFiles.txt https://github.com/chemfiles/chemfiles/blob/99486730d4849656308516c6f7ed60b74fd575bc/CMakeLists.txt#L80

do you see any message at cmake configure time?

**Comment by sguionni** [comment]
Yes the message is printed.

`PS C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\Hostx64\x64> .\cl.exe
Compilateur d'optimisation Microsoft (R) C/C++ version 19.25.28614 pour x64`

**Comment by Luthaf** [comment]
Ok, that's strange. 

Do you also see a message if you add a `#warning "here"` inside the `#ifdef`?
https://github.com/chemfiles/chemfiles/blob/99486730d4849656308516c6f7ed60b74fd575bc/include/chemfiles/UnitCell.hpp#L10-L12

Also, are you able to build chemfiles alone (not part of your project)? You can do this by running these commands in cmd.exe/PowerShell

```powershell
git clone https://github.com/chemfiles/chemfiles
cd chemfiles
mkdir build
cd build
cmake ..
cmake --build . --config Debug
```

**Comment by sguionni** [comment]
I'm already builing chemfiles alone with VS before including it in my project as a lib
#warning does not exists in VS but it informs me that CHEMFILES_WINDOWS is correctly defined:

![qsdqsdd](https://user-images.githubusercontent.com/3633017/81274342-713fa000-9050-11ea-8339-7f44266d1590.jpg)

**Comment by Luthaf** [comment]
You can also try with `#error "here"`, I am pretty sure I used this one with MSVC.

Are you certain the INFINITE causing the error is the one in UnitCell.hpp? Could you share the full error you get?

**Comment by sguionni** [comment]
Yes i'm sure if i comment this line :
![2020-05-07_11h29_36](https://user-images.githubusercontent.com/3633017/81278543-1e68e700-9056-11ea-9430-68b72d902baa.png)
 i got this error:
![2020-05-07_11h29_54](https://user-images.githubusercontent.com/3633017/81278560-23c63180-9056-11ea-9a65-b3d1b6f5b26d.png)

**Comment by sguionni** [comment]
I will try to build in command line instead of using VS.

**Comment by Luthaf** [comment]
I can not reproduce this on the latest master with cmake 3.16.1 and MSVC 19.16.27032.1. Could you copy/paste a full build log, from cmake configuration all the way to the error, with the exact commands you run? You can use a [gist](https://gist.github.com/) to copy/paste large amount of text.

I'll try to install VS 2019 to see if that's where the error comes from.

**Comment by Luthaf** [comment]
> I'll try to install VS 2019 to see if that's where the error comes from.

It is compiling fine on my VM, using Visual Studio 2019 Community editon & CMake integration. Perhaps there is a problem with your VS configuration?

**Comment by Luthaf** [comment]
@sguionni did you figure out the origin of this issue on your side?

**Comment by sguionni** [comment]
I just had to add this line to my CMakeLists.txt:
`add_definitions(-DCHEMFILES_WINDOWS)`

**Comment by Luthaf** [comment]
Your `CMakeLists.txt` meaning the CMakeLists.txt file of your program?  If so, I think I understand where the issue comes from! Are you using a pre-built chemfiles, i.e. `find_package(Chemfiles)`, and not building chemfiles as part of your project, i.e. `add_subdirectory(chemfiles)`?

**Comment by sguionni** [comment]
Chemfiles is included by this way in cmake file:

`
target_link_libraries(VTX PRIVATE chemfiles)
target_include_directories(VTX PRIVATE ${PATH_LIB}/chemfiles/include)
`

chemfiles.lib is built before, i just link .lib and includes

**Comment by Luthaf** [comment]
Ok, I think I understand where the issue comes from, see #341!

**Comment by Luthaf** [comment]
This should be fixed now (meaning you don't have to define `CHEMFILES_WINDOWS` yourself). Let me know if the issue persists after re-installing chemfiles!

**Comment by sguionni** [comment]
It's ok. Thanks!
