### ISSUE TITLE
Use double instead of floats for positions/velocities?

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#34]
This uses more memory, but have multiple advantages:
- Better support for simulations codes, with no double -> float conversion needed;
- Support for restart-style files, like the restart convention for NetCDF.

**Comment by maxlevesque** [comment]
You sure of that move? Seems to me there's a big move toward so-called single precision these days. Look at gromacs for instance. This tendency is driven by the GPU and MIC world where vectorization is so important.

**Comment by Luthaf** [comment]
I am not sure, that is why there is the `discussion` label! What bug me with single precision is that Chemfiles will never support any format with double precisions.

Another possibility would be to somehow dynamically switch precision as needed, but this would make the library API a nightmare. Or have different single/double compilation mode, like FFTW3, but then we get ABI incompatibilities.
