### ISSUE TITLE
“orthorhombic” takes two h's

### ISSUE THREAD

**Issue by fxcoudert** [chemfiles/chemfiles#354]
See for example [wikipedia](https://en.wikipedia.org/wiki/Orthorhombic_crystal_system).
It should be “orthorhombic” not “orthorhombic” in several places, in particular in `UnitCell.cpp`: https://github.com/chemfiles/chemfiles/blob/7d744d67e8bc7245613534a2a303aac9d836eb5e/src/UnitCell.cpp#L252

**Comment by Luthaf** [comment]
Whoops, you are right!

```
$ rg orthorombic
src/UnitCell.cpp
252:Vector3D UnitCell::wrap_orthorombic(const Vector3D& vector) const {
274:            return wrap_orthorombic(vector);

include/chemfiles/UnitCell.hpp
190:    /// For an orthorombic unit cell, this make sure that all the vector
198:    /// Wrap a vector in orthorombic cell
199:    Vector3D wrap_orthorombic(const Vector3D& vector) const;
```

None of these are part of the public API, so it should be a matter of search & replace! Tagging as 'Help wanted' since that should be a very good first issue =)
