### ISSUE TITLE
Support segment/segid in PDB reader

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#362]
```
REMARK original generated coordinate pdb file
ATOM      1  N   ALA A   1      -9.229 -14.861  -5.481  1.00  0.00      P1   N
ATOM      2  HT1 ALA A   1     -10.048 -15.427  -5.569  1.00  0.00      P1    
ATOM      3  HT2 ALA A   1      -9.488 -13.913  -5.295  1.00  0.00      P1    
ATOM      4  HT3 ALA A   1      -8.652 -15.208  -4.741  1.00  0.00      P1    
ATOM      5  CA  ALA A   1      -8.483 -14.912  -6.726  1.00  0.00      P1   C
ATOM      6  HA  ALA A   1      -8.185 -15.947  -6.894  1.00  0.00      P1   H
ATOM      7  CB  ALA A   1      -9.383 -14.465  -7.880  1.00  0.00      P1   C
ATOM      8  HB1 ALA A   1     -10.428 -14.602  -7.600  1.00  0.00      P1   H
ATOM      9  HB2 ALA A   1      -9.200 -13.413  -8.098  1.00  0.00      P1   H
ATOM     10  HB3 ALA A   1      -9.164 -15.063  -8.765  1.00  0.00      P1   H
ATOM     11  C   ALA A   1      -7.227 -14.047  -6.599  1.00  0.00      P1   C
ATOM     12  OT1 ALA A   1      -7.203 -13.641  -5.686  0.00  0.00      P1    
ATOM     13  OT2 ALA A   1      -6.717 -14.085  -7.458  0.00  0.00      P1    
ATOM     14  N   GLY A   1       5.512 -12.329  -3.475  1.00  0.00      P2   N
ATOM     15  HT1 GLY A   1       5.944 -11.668  -4.089  0.00  0.00      P2    
ATOM     16  HT2 GLY A   1       5.288 -11.890  -2.605  0.00  0.00      P2    
ATOM     17  HT3 GLY A   1       4.682 -12.694  -3.897  0.00  0.00      P2    
ATOM     18  CA  GLY A   1       6.437 -13.422  -3.229  1.00  0.00      P2   C
ATOM     19  HA1 GLY A   1       7.311 -13.011  -2.742  1.00  0.00      P2    
ATOM     20  HA2 GLY A   1       6.707 -13.894  -4.174  1.00  0.00      P2   H
ATOM     21  C   GLY A   1       5.818 -14.462  -2.292  1.00  0.00      P2   C
ATOM     22  OT1 GLY A   1       4.895 -14.167  -2.043  0.00  0.00      P2    
ATOM     23  OT2 GLY A   1       6.477 -15.199  -2.143  0.00  0.00      P2    
END
```
What differentiates one structure from the next is the "segment", which in this case is P1 or P2.

The segment identifiers are not standard PDB formats, but are additions used by Namd and Charmm to their simulation formats, and yes, it is an addition to that 73-76 empty spaces, with a maximum of four characters.

_Originally posted by @leandromartinez98 in https://github.com/chemfiles/chemfiles/issues/361#issuecomment-664492964_

**Comment by frodofine** [comment]
This shouldn't be difficult to add!

**Comment by leandromartinez98** [comment]
In case you do implement this, I would suggest call the selection syntax `segname` to follow the same syntax used in VMD. VMD is the package used mostly by NAMD users, and since this is a feature mostly known by those users, using the same syntax is probably nice.

**Comment by Luthaf** [comment]
I envision this as being an atom property, like chainid/chainname. So the selection syntax would be `[segnam] == PROT`

**Comment by Luthaf** [comment]
Are segment a property of a given atom or a given residue? I.e. can we have different segments for the same residue?

**Comment by leandromartinez98** [comment]
No, every atom of the same residue (and even a whole protein) can only belong to (thus, have) the same segment.

Most generally, a segment is a subset of the system whose topology (connectivity, angles, etc) can be defined independently
of the rest of the system. Thus, no molecule can be split between segments. Typically, the organization is such that each protein chain belongs to a segment, the solvent molecules to other segment, ions to other segment, etc.

**Comment by Luthaf** [comment]
ok, thanks! It would make sense making it a Residue property then.
