### ISSUE TITLE
Deal with vector permutation in the cell matrix

### ISSUE THREAD

**Issue by Luthaf** [chemfiles/chemfiles#384]
Chemfiles' latest addition allows constructing cells from arbitrary matrices. This makes life hard for this PR (diagonal for non--infinite cells might be all zeros) and might also have some issues in itself (e.g. `UnitCell({ 0, 0, 1, /**/ 1, 0, 0, /**/ 0, 1, 0 })` is erroneously(?) triclinic).

_Originally posted by @ezavod in https://github.com/chemfiles/chemfiles/issues/381#issuecomment-738287888_

**Comment by Luthaf** [comment]
I agree that if we accept `UnitCell({ 0, 0, 1, /**/ 1, 0, 0, /**/ 0, 1, 0 })` as a unit cell, then it should be orthorhombic. I'm not sure if the best solution here is to reject such cells at construction time, or try to deal with them. I would tend to reject them, at least until a proper use case for them come around. What do you think?

**Comment by ezavod** [comment]
Thanks for transferring my comment into its own issue.
> reject such cells at construction time, or try to deal with them

I think the hardest part is to find a condition for these "problematic" matrices. An easy solution would be to allow upper triangular matrices only. But this might not allow rotated triclinic cells, effectively reverting #368, does it? Alternatively we can check whether matrices are diagonalizable. IMHO this is rather tedious but would be also a way to deal with such matrices.
I would also tend to reject them, but I don't know how common rotated cells in  NPT simulations are. AFAIK e.g. Gromacs always writes upper triangular matrices.
