### ISSUE TITLE
Wrong detection of file ends in text files

### ISSUE THREAD

**Issue by ezavod** [chemfiles/chemfiles#392]
Most text based formats seem to wait for a `FileError` as an indication for reaching the end of the file. See e.g. [SDF](https://github.com/chemfiles/chemfiles/blob/f913099990ad972530911da40d28507cc66c6b01/src/formats/SDF.cpp#L365-L374) or [GRO](https://github.com/chemfiles/chemfiles/blob/db891d495dd693fb2794b75c2379719ee98a3d50/src/formats/GRO.cpp#L281-L302).
Seemingly this is most prevalent in `forward()` and should be easy to find by searching for `FileError`.
My best guess is that this became broken in #271 by changes in `TextFile::readline()`. Since then an empty string is returned instead of a raised exception.

**Comment by Luthaf** [comment]
You mean a `FileError` is no longer thrown on end of file, breaking some formats? Do you have a specific example showing the breakage?

**Comment by ezavod** [comment]
> You mean a FileError is no longer thrown on end of file, [...]?

Yes, while writing the LAMMPS reader I wanted to skip all lines until a specific entry is found or the end of the file is reached. Using a `try ... catch` block, as it's done in other text formats, resulted in an infinite loop because an exception is never thrown.

> Do you have a specific example showing the breakage?

This does not actually seem to break anything important in existing code. All the loops that rely on the exception for an early exit are eventually terminated by an other condition, thus no infinite loops. The GRO reader, for example, tries to read all atoms, and would throw an error if there are no more atoms left. Currently this error is not thrown if we try to read past the end (haven't tested yet), but the loop terminates anyway if the number of expected atoms is reached. I will try to look at a few testcases in the coming days to better grasp the implications of this.

In general this seems to be more of a code quality issue rather than an actual bug. In the absence of docs for adding new formats most people would reasonably try to use some existing formats as starting point. For text formats I typically look at the GRO file because it appears alphabetically at the top (and I'm too lazy to scroll down :D). In there the catch is explicitly commented with "No more line left in the file" i.e. reached end of file, which might be confusing for new contributors.

**Comment by Luthaf** [comment]
Completely agree that this is a code quality problem 😄. I think that we should move a bit away from using exceptions for normal things like reaching the end of a file; so my preferred fix here would be to change the formats to explicitly check for `file.eof()`. This would also make the code a bit clearer!
