### ISSUE TITLE
Add support for atom labels in PDB files

### ISSUE THREAD

**Issue by pgbarletta** [chemfiles/chemfiles#40]
Modify `Atom` concept to hold atom labels. 
---
Main TODOs:
- Create `label_` variable and read it from columns 13-16 of the PDB format file. 
- Rename `name_` variable to `element_` and read it  from columns 78-80 in the PDB format file.
Then, for consistency, continue replacing   `name_` with `element_` in the rest of the project.

**Comment by Luthaf** [comment]
Cf https://github.com/chemfiles/chemfiles/issues/35#issuecomment-249930500 for the origin of this.

**Comment by Luthaf** [comment]
Closed by #41
