### ISSUE TITLE
Is chemfiles thread-safe (e.g. with OpenMP)?

### ISSUE THREAD

**Issue by ShoubhikRaj** [chemfiles/chemfiles#418]
I am using the C++ API of chemfiles in my code for analysis of a MD trajectory. There are a lot of data to process so it would be good if parallelisation can be done in the code. I **do not** mean that chemfiles should run in parallel, but that I wish to call chemfiles in a parallel code.

My preliminary test code, parallelised with OpenMP, seems to work correctly and produce that same results as the sequential code. However, I wish to know which part of chemfiles are thread safe, and which part are not (if there are any), so that I don't run into weird problems in future.

For example, is it safe to access different frames from different threads, from the same trajectory using the `trajectory.read_step(i)`? Is it safe to call `frame.angle(i,j,k)` with different values of `i`,`j` and `k`  from different threads for a common (shared) frame object?

I could not find anything on this in the documentation, so any advice would be very helpful.

**Comment by Luthaf** [comment]
So chemfiles is mostly thread-safe, in part thanks to Rust running the test suite in parallel and allowing us to catch a bunch of parallelism related issues when creating [chemfiles.rs](https://github.com/chemfiles/chemfiles.rs). In particular, all global resources (logger, registry of formats, ...) are already protected by mutex.

Local objects are a different question. Here, most `const` function should be fine to call from different threads on the same object, except for `Topology::angles`/`Topology::dihedrals`/`Topology::impropers` which lazily update the list after changes to the bond list. This includes calling `frame.angle(i, j, k)` from different threads.

Non-const function should not be called on the same object from different threads since they modify internal state. That's the case for example of `trajectory.read_step(i)`. However, if you want to read a file in parallel from multiple threads, you can create multiple `Trajectory` object, and have each one of these read a different step. For the best performance here you will want to use binary formats which can directly read separate steps without skipping around the file.

Hope that helps, and I'll leave this issue open to add something like this to the documentation!

**Comment by ShoubhikRaj** [comment]
@Luthaf Thank you!

I am also bit confused about why `trajectory.read_step(i)` modifies the internal state. Shouldn't it only access the `i`th step of the trajectory, like an array? `trajectory.read()` would change the position of the iterator/pointer I imagine, so I can understand why it is thread unsafe.

In any case, how do you think I should open the trajectory from multiple frames. For example would the following work?

```
#pragma omp parallel
{
   auto trj = chemfiles::Trajectory("file.dcd");
   size_t num_steps = trj.nsteps()

   #pragma omp for
   for (size_t n=0; n<num_steps; ++n) {
      auto this_frame = trj.read_step(n);
      // calculation
   }
}
```
Or do I need to copy the trajectory object with ``#pragma omp parallel firstprivate(trj)` for each thread or something similar to that?

All of this help is greatly appreciated.

**Comment by ShoubhikRaj** [comment]
I just tested the above code, and it does not seem to be working. In fact I tried multiple ways including `#pragma omp firstprivate(trj)` and `#pragma omp private`, but nothing works.

When I try to open the same file from multiple frames, I get this error:
```
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) read_dcdheader: premature end of file
dcdplugin) read_dcdheader: premature end of file
```
It raises an unhandled exception and the program crashes.

If I try to read the same trajectory from multiple threads, I get the error:
```
dcdplugin) read_dcdstep: corruption or unrecognized file structure
dcdplugin) read_dcdstep: corruption or unrecognized file structure
dcdplugin) read_dcdstep: corruption or unrecognized file structure
dcdplugin) read_dcdstep: corruption or unrecognized file structure
```
With `firstprivate(trj)` which would copy the variable `trj` into each thread does not compile. It seems that doing `auto trj = chemfiles::Trajectory("testfile.dcd")` does not give an actual variable `trj` but some kind of reference. When trying to copy it, the compiler says that it refers to a function that no longer exists.

**Comment by Luthaf** [comment]
> I am also bit confused about why trajectory.read_step(i) modifies the internal state. Shouldn't it only access the ith step of the trajectory, like an array?

`trajectory.read_step(i)` may also needs to change the position of the cursor inside the file, since we still need to change the position of in the file before calling `fread` (either to the start of the frame for text format, or to the relevant array offset for binary files).

> In any case, how do you think I should open the trajectory from multiple frames. For example would the following work?

I'm not familiar enough with OpenMP, but I think you would need to create a new Trajectory object is each threads, just copying an existing file is not enough (each trajectory object must have a different file descriptor). Something like this with 
std::thread might work:

```cpp
void run_calculation(size_t step) {
    auto trj = chemfiles::Trajectory("file.dcd");
    auto frame = trj.read_step(step);

    // calculation ...
}

int main() {
    // get the number of threads to start
    auto trj = chemfiles::Trajectory("file.dcd");
    size_t num_steps = trj.nsteps();
    trj.close();

    auto threads = std::vector<std::thread>();
    for (size_t n=0; n<num_steps; ++n) {
        auto thread = std::thread(do_calculation, n);
        threads.push_back(std::move(thread));
    }

    for (auto& thread: threads) {
        thread.join();
    }
}
```

Then, since you are using the DCD format, there is actually another potential set of issues related to the molfile DCD reader. I'll need to read the code carefully, but they might introduce some issues with threads as well. (Another good reason to replace this code!)

----

Since I/O does not improves a lot with multithreading (and reading from the same file from a lot of threads can even get a lot slower), it might also be interesting in your case to first read frames in memory and then move the calculation to multithreaded code: 

```cpp
auto trj = chemfiles::Trajectory("file.dcd");
size_t num_steps = trj.nsteps();

auto frames = std::vector<chemfiles::Frame>();
for (size_t n=0; n<num_steps; ++n) {
    auto frame = trj.read_step(n);
    frames.push_back(std::move(frame));
}

#pragma omp for
for (size_t n=0; n<num_steps; ++n) {
    // calculation
}
```

If you want to avoid out of memory issue, you can also create multiple chunks and work on one chunk at the time:

<details>

```cpp
auto trj = chemfiles::Trajectory("file.dcd");
size_t num_steps = trj.nsteps();
auto chunk_size = 100;
auto n_chunks = num_steps / chunk_size;

auto frames = std::vector<chemfiles::Frame>();

for (size_t chunk=0; chunk<n_chunks; chunk++) {
    frames.clear();

    auto start = chunk * chunk_size;
    auto stop = (chunk + 1) * chunk_size
    for (size_t n=start; n<stop; ++n) {
        auto frame = trj.read_step(n);
        frames.push_back(std::move(frame));
    }

    #pragma omp for
    for (size_t i=0; i<frame.size(); ++i) {
        // calculation
    }
}

// deal with the remaining frames
frames.clear();
for (size_t n=n_chunks * chunk_size; n<n_steps; ++n) {
    auto frame = trj.read_step(n);
    frames.push_back(std::move(frame));
}

#pragma omp for
for (size_t i=0; i<frame.size(); ++i) {
    // calculation
}
```

</details>

**Comment by ShoubhikRaj** [comment]
@Luthaf Thank you for the detailed comments.

>I'm not familiar enough with OpenMP, but I think you would need to create a new Trajectory object is each threads, just copying an existing file is not enough (each trajectory object must have a different file descriptor).

So does that mean every trajectory object must open a different file? i.e. Do I need to make copies the physical file on the disk?

What I did with OpenMP was also creating private Trajectory objects for each thread, each being supplied with the same file name. But it did not work, I got the "premature end of file" error as I mentioned in the thread before. I am not very familiar with std::thread unfortunately.

**Comment by Luthaf** [comment]
I'm not sure what is going wrong for you. I managed to compile this program

```cpp
#include <cstdio>
#include <omp.h>

#include "chemfiles.hpp"

int main() {
    #pragma omp parallel
    {
        auto trj = chemfiles::Trajectory("tests/data/dcd/water.dcd");
        size_t num_steps = trj.nsteps();

        #pragma omp for
        for (size_t n=0; n<num_steps; ++n) {
            auto frame = trj.read_step(n);
            printf("frame %d with %d atoms in thread %d\n", n, frame.size(), omp_get_thread_num());

            // calculation
        }
    }
}
```

and running it on the DCD file we use for tests (https://github.com/chemfiles/tests-data/blob/master/dcd/water.dcd), I get this output:

```
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
frame 0 with 297 atoms in thread 0
frame 1 with 297 atoms in thread 0
frame 2 with 297 atoms in thread 0
frame 3 with 297 atoms in thread 0
frame 4 with 297 atoms in thread 0
frame 5 with 297 atoms in thread 0
frame 6 with 297 atoms in thread 0
frame 7 with 297 atoms in thread 0
frame 8 with 297 atoms in thread 0
frame 9 with 297 atoms in thread 0
frame 10 with 297 atoms in thread 0
frame 11 with 297 atoms in thread 0
frame 12 with 297 atoms in thread 0
frame 13 with 297 atoms in thread 1
frame 26 with 297 atoms in thread 2
frame 27 with 297 atoms in thread 2
frame 28 with 297 atoms in thread 2
frame 29 with 297 atoms in thread 2
frame 14 with 297 atoms in thread 1
frame 30 with 297 atoms in thread 2
frame 15 with 297 atoms in thread 1
frame 31 with 297 atoms in thread 2
frame 16 with 297 atoms in thread 1
frame 17 with 297 atoms in thread 1
frame 18 with 297 atoms in thread 1
frame 32 with 297 atoms in thread 2
frame 19 with 297 atoms in thread 1
frame 33 with 297 atoms in thread 2
frame 20 with 297 atoms in thread 1
frame 34 with 297 atoms in thread 2
frame 21 with 297 atoms in thread 1
frame 35 with 297 atoms in thread 2
frame 22 with 297 atoms in thread 1
frame 36 with 297 atoms in thread 2
frame 23 with 297 atoms in thread 1
frame 37 with 297 atoms in thread 2
frame 24 with 297 atoms in thread 1
frame 25 with 297 atoms in thread 1
frame 38 with 297 atoms in thread 2
frame 39 with 297 atoms in thread 3
frame 40 with 297 atoms in thread 3
frame 41 with 297 atoms in thread 3
frame 42 with 297 atoms in thread 3
frame 43 with 297 atoms in thread 3
frame 52 with 297 atoms in thread 4
frame 44 with 297 atoms in thread 3
frame 53 with 297 atoms in thread 4
frame 45 with 297 atoms in thread 3
frame 54 with 297 atoms in thread 4
frame 46 with 297 atoms in thread 3
frame 55 with 297 atoms in thread 4
frame 47 with 297 atoms in thread 3
frame 56 with 297 atoms in thread 4
frame 48 with 297 atoms in thread 3
frame 57 with 297 atoms in thread 4
frame 49 with 297 atoms in thread 3
frame 58 with 297 atoms in thread 4
frame 50 with 297 atoms in thread 3
frame 59 with 297 atoms in thread 4
frame 51 with 297 atoms in thread 3
frame 60 with 297 atoms in thread 4
frame 61 with 297 atoms in thread 4
frame 62 with 297 atoms in thread 4
frame 63 with 297 atoms in thread 4
frame 64 with 297 atoms in thread 5
frame 65 with 297 atoms in thread 5
frame 66 with 297 atoms in thread 5
frame 67 with 297 atoms in thread 5
frame 68 with 297 atoms in thread 5
frame 69 with 297 atoms in thread 5
frame 70 with 297 atoms in thread 5
frame 71 with 297 atoms in thread 5
frame 72 with 297 atoms in thread 5
frame 73 with 297 atoms in thread 5
frame 74 with 297 atoms in thread 5
frame 75 with 297 atoms in thread 5
frame 76 with 297 atoms in thread 6
frame 77 with 297 atoms in thread 6
frame 78 with 297 atoms in thread 6
frame 79 with 297 atoms in thread 6
frame 80 with 297 atoms in thread 6
frame 81 with 297 atoms in thread 6
frame 82 with 297 atoms in thread 6
frame 83 with 297 atoms in thread 6
frame 88 with 297 atoms in thread 7
frame 84 with 297 atoms in thread 6
frame 89 with 297 atoms in thread 7
frame 85 with 297 atoms in thread 6
frame 90 with 297 atoms in thread 7
frame 86 with 297 atoms in thread 6
frame 91 with 297 atoms in thread 7
frame 87 with 297 atoms in thread 6
frame 92 with 297 atoms in thread 7
frame 93 with 297 atoms in thread 7
frame 94 with 297 atoms in thread 7
frame 95 with 297 atoms in thread 7
frame 96 with 297 atoms in thread 7
frame 97 with 297 atoms in thread 7
frame 98 with 297 atoms in thread 7
frame 99 with 297 atoms in thread 7
```

Everything seems to be working fine, the file is opened multiple times (`dtrace` shows multiple `open` syscall for this file), and each thread reads a different set of frames. Could you try reproducing this example, with the same file? This way we can know whether there is a difference with your setup/os/..., or if a different file make this code behave differently.

**Comment by ShoubhikRaj** [comment]
@Luthaf I compiled the same code on MSVC++ 2019 (except changing `size_t n=0` to `long long n =0` because MSVC++ is still stuck in ancient OpenMP 2.0, and changing the name of the dcd file).
```
C:\Users\Public> cl /openmp /I.\include /MD /EHsc omp_dcdtest.cpp /link .\lib\chemfiles.lib WS2_32.lib Advapi32.lib
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29913 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

omp_dcdtest.cpp
omp_dcdtest.cpp(15): warning C4477: 'printf' : format string '%d' requires an argument of type 'int', but variadic argument 1 has type '__int64'
omp_dcdtest.cpp(15): note: consider using '%lld' in the format string
omp_dcdtest.cpp(15): note: consider using '%Id' in the format string
omp_dcdtest.cpp(15): note: consider using '%I64d' in the format string
omp_dcdtest.cpp(15): warning C4477: 'printf' : format string '%d' requires an argument of type 'int', but variadic argument 2 has type 'size_t'
omp_dcdtest.cpp(15): note: consider using '%zd' in the format string
Microsoft (R) Incremental Linker Version 14.28.29913.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:omp_dcdtest.exe
.\lib\chemfiles.lib
WS2_32.lib
Advapi32.lib
omp_dcdtest.obj
   Creating library omp_dcdtest.lib and object omp_dcdtest.exp

C:\Users\Public> set OMP_NUM_THREADS=4
C:\Users\Public> omp_dcdtest.exe
dcdplugin) read_dcdheader: premature end of file
dcdplugin) read_dcdheader: premature end of file
```
So, it does not work with MSVC++.

Then I tried Intel's LLVM C/C++ compiler (which is much more standards compliant) with your original code, and I still get the same error.

The dcd file, along with the corresponding pdb and psf files are attached here: [testfile.zip](https://github.com/chemfiles/chemfiles/files/7080837/testfile.zip).

**Comment by Luthaf** [comment]
I'm able to read the file without issues on macOS, using clang-12 as compiler.

What is happening here might be related to file sharing on windows. The DCD code opens the file disallowing sharing it with other processes, but I don't know if this applies to multiple threads as well.
https://github.com/chemfiles/molfiles/blob/56b83104c042632f331e52f954bd77873cae2ae8/src/fastio.h#L102

Could you try re-compiling chemfiles replacing `external/molfiles.tar.gz` with this version ([molfiles.tar.gz](https://github.com/chemfiles/chemfiles/files/7082542/molfiles.tar.gz)), where I changed the above line to `sharing = FILE_SHARE_READ;`, and then re-run the code? If that work, I can prepare a better patch =)

**Comment by ShoubhikRaj** [comment]
@Luthaf  It works now. I changed the file and recompiled:

```
C:\Users\Public> omp_dcdtest.exe 
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) detected standard 32-bit DCD file of native endianness
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
dcdplugin) CHARMM format DCD file (also NAMD 2.1 and later)
frame 0 with 401 atoms in thread 0
frame 1 with 401 atoms in thread 0
frame 2 with 401 atoms in thread 0
frame 3 with 401 atoms in thread 0
frame 4 with 401 atoms in thread 0
frame 5 with 401 atoms in thread 0
frame 10 with 401 atoms in thread 1
frame 6 with 401 atoms in thread 0
frame 11 with 401 atoms in thread 1
frame 7 with 401 atoms in thread 0
frame 12 with 401 atoms in thread 1
frame 8 with 401 atoms in thread 0
frame 13 with 401 atoms in thread 1
frame 9 with 401 atoms in thread 0
frame 14 with 401 atoms in thread 1
frame 15 with 401 atoms in thread 1
frame 16 with 401 atoms in thread 1
frame 20 with 401 atoms in thread 2
frame 17 with 401 atoms in thread 1
frame 21 with 401 atoms in thread 2
frame 18 with 401 atoms in thread 1
frame 22 with 401 atoms in thread 2
frame 19 with 401 atoms in thread 1
frame 23 with 401 atoms in thread 2
frame 24 with 401 atoms in thread 2
frame 30 with 401 atoms in thread 3
frame 25 with 401 atoms in thread 2
frame 31 with 401 atoms in thread 3
frame 26 with 401 atoms in thread 2
frame 27 with 401 atoms in thread 2
frame 32 with 401 atoms in thread 3
frame 28 with 401 atoms in thread 2
frame 33 with 401 atoms in thread 3
frame 29 with 401 atoms in thread 2
frame 34 with 401 atoms in thread 3
frame 35 with 401 atoms in thread 3
frame 36 with 401 atoms in thread 3
frame 37 with 401 atoms in thread 3
frame 38 with 401 atoms in thread 3
frame 39 with 401 atoms in thread 3
```

Meanwhile, I had also found another way of running it with openmp, without opening the same file multiple times. This also works successfully:
```
#include <iostream>
#include "chemfiles.hpp"

#include <cstdio>
#include <omp.h>

#include "chemfiles.hpp"

int main() {

    auto trj = chemfiles::Trajectory("testfile.dcd");
    size_t num_steps = trj.nsteps();
        
    #pragma omp parallel
    {
        auto frame = chemfiles::Frame(); // create empty frame object
        #pragma omp for
        for (long long n=0; n<num_steps; ++n) {
            #pragma omp critical
            {
                frame = trj.read_step(n); // only executed by one thread at a time
            }
            printf("frame %d with %d atoms in thread %d\n", n, frame.size(), omp_get_thread_num());

        // calculation
        }
    }
}
```
Thanks a lot!!

**Comment by Luthaf** [comment]
Ok, good to know! I'll update the bundled molfiles to include this fix
