### ISSUE TITLE
Trajectory reading in C++ causes continuous memory allocation, possible memory leak

### ISSUE THREAD

**Issue by ShoubhikRaj** [chemfiles/chemfiles#421]
When iterating through every frame of a trajectory in a `for` or `while` loop, the program asks for more and more memory. This is either a design fault or a memory leak. Because there is no need to store the frame of the previous iteration, that memory should be freed.

Example C++ code to reproduce this behaviour (works on both Linux and Windows):
```
#include "chemfiles.hpp"
#include <iostream>
#include <chrono>
#include <thread>

chemfiles::Trajectory trj("testfile.dcd"); // testfile.dcd is an NAMD DCD trajectory

int count = 0;
while (!trj.done()) {
   auto frame = trj.read();
   count++;
   std::cout << "frame " << count << " read.\n";
   std::this_thread::sleep_for(std::chrono::milliseconds(2000));
   auto positions_this_frame = frame.positions();
}
```
When compiled with Visual Studio 2019 (MSVC++ v19.28), and checking for the memory usage with time with the profiler, I get this:

![image](https://user-images.githubusercontent.com/17470159/131248109-7e91faa6-7c73-4a98-9f3c-5a037c4cfe7f.png)

After the initialization, the program allocates more memory with every frame read. (The program sleeps for 2 seconds in each iteration to make the graph clearer).

When frame reading stops (after I manually hit ctrl+c) the memory acquiring also stopped. This should not happen because `frame` is a variable local to the for loop, so it should disappear, along with any memory it holds, when each iteration ends. But clearly that is not happening, i.e. any frame read previously is also held somewhere in the memory.

This is very problematic for analysing large trajectory files (~2 GB) because all of that data cannot be loaded into the RAM all at once. It should be that only one frame is held in the memory for each iteration, so that there is no overflow.

I also tested similar code with g++ (GNU 9.3.0) on Gentoo OS, and it still runs into the same issue. The program is killed by Linux because it asks for too much memory. I do not have much experience with debuggers on Linux, so I cannot post memory vs time plots, but I am pretty sure the same thing is happening there as well.

The problem also persists with a `for` loop with `Trajectory.read_step()` as well. It might be that this is only a problem with DCD files, I have not checked with any other formats. I have looked through the C++ API documentation, and couldn't find anything about freeing memory explicitly, so I assume that the memory freeing is intended to be automatically handled when the variable goes out of scope.

**Comment by Luthaf** [comment]
That's a known issue of the Molfile based readers, used in particular for DCD files. See #370 for another instance of the same issue. Basically what's happening is that we are emulating "read_step" which is not supported by the molfile readers by caching all frames until the requested step, and using this cache if the user request a previous frame ([see the code around here](https://github.com/chemfiles/chemfiles/blob/b6b75c3780120628bd8dd29e174d361bd48fc9bd/src/formats/Molfile.cpp#L186-L195)).

Unfortunately, writing a better DCD reader is a lot of work. We already have a PR (#389) which started the work toward this goal, but needs to be updated with the latest master changes. Given that this feature is requested a lot for chemfiles, I'll try to bump this feature up in my TODO list.

**Comment by ShoubhikRaj** [comment]
@Luthaf I read the code. With my limited C++ knowledge, it seems that you are reading the frames and storing them into a vector.

But this makes reading large trajectory files almost impossible without having an impractically large RAM. For example I was reading a 2 GB DCD file with my code, and even after assigning 6 GB RAM to the process, it ran out of memory.

Wouldn't it be better instead to remove the frame storing from the `Trajectory.read()`, and for `Trajectory.read_step(i)`, iterate through the trajectory from the beginning with a loop, without storing, until the `i`th frame is obtained, and then break the loop? I think this would waster a little bit of CPU power and some disk I/O, but would avoid the issue of memory overflow.

**Comment by Luthaf** [comment]
We are only doing this hack for Molfile based readers, all other formats do not suffer from this issue (for example, if you can read very large TNG, NetCDF, … files without filling up your memory).

We could try to revert 8f4efe85419e93dd47d18b900826f426c69c2f37 and do what you suggest, but I would rather spend my time to make this format work properly with chemfiles' API instead of piling up hacks 😃. However, if you send a PR making this change I'm open to merge it to have something working until we get a better DCD reader! Looping through the frames is not quite enough though, you would need to close & reopen the file for each call to `read_step` in case a user calls `trajectory.read_step(33)` and then `trajectory.read_step(2)`.

**Comment by ShoubhikRaj** [comment]
@Luthaf Yes you are right. I will keep an eye out for when the new DCD reader is implemented in chemfiles.

As you mentioned other formats do not have this problem, I converted my DCD to TRR and then used that for the analysis - this works correctly.

Feel free to close this issue if you want to.

**Comment by Luthaf** [comment]
Let's close this issue and use #370 to track the DCD work
