### ISSUE TITLE
Add a frame property indicating if coordinates are unwrapped

### ISSUE THREAD

**Issue by SamTov** [chemfiles/chemfiles#442]
Is there a method in chemfiles to confirm whether the coordinates being read in are wrapped or unwrapped?

**Comment by Luthaf** [comment]
In general no, there is no way to do this. It really depends on the file format being read, and how data was stored inside. You could check if some coordinates are outside the range of the unit cell.

For LAMMPS trajectory in particular, we try to read unwrapped coordinates first, then unwrapped scaled/fractional coordinates (which are rescaled to cartesian coordinates), then wrapped coordinates, then scaled coordinates. Which one will be read will depend on what's in the file, and that ultimately depends on what the user requested in the LAMMPS input. 

---

What could be interesting to do would be to add a new frame property indicating whether coordinates are wrapped or unwrapped.

Apart from LAMMPS trajectories, do you know another format which explicitly separate wrapped & unwrapped coordinates?

**Comment by SamTov** [comment]
In my case, I had read in a water simulation from GROMACS so using an `.xtc` file for the trajectory and `.gro` for topology. When I perform an MSD analysis the 'unwrapped coordinates` look very wrapped, i.e. they form a flat line in the MSD. If I treat what chemfiles gives me as wrapped and then unwrap them I get good MSDs with a nice diffusion coefficient.

**Comment by Luthaf** [comment]
Right, so chemfiles is only performing I/O, and giving you what's in the XTC. From what you are saying, it seems that coordinates were stored wrapped in this file (I think this is the default for XTC file). If you need unwrapped coordinates you should manually unwrap them. Depending how you do this unwrapping, you should be able to always apply it on data produced by chemfiles, since unwrapping unwrapped coordinates should not change them.

**Comment by Luthaf** [comment]
> Ahh so to be sure here, chemfiles will never perform an unwrapping operation for you? If unwrapped coordinates exists, that is what will be returned, but if not, no manual unwrapping will take place within chemfiles?

That's a very good assessment of the situation. We try to return the most precise data possible, but we will not invent/modify data in ways that could introduce floating points errors.

> I think it would still be useful for our case to know if the data being returned is unwrapped or not but this is a nice start.

That could be a frame property set whenever possible. Would you have time to send a short PR adding this property for the LAMMPS trajectory format?
