### ISSUE TITLE
Multi-threaded trajectory reading fails occasionally

### ISSUE THREAD

**Issue by ezavod** [chemfiles/chemfiles#448]
Sometime the `trajectory` test fails, but not always (see [this action run](https://github.com/chemfiles/chemfiles/runs/6118887187?check_suite_focus=true#step:9:94)).
This is caused by the [DCD test](https://github.com/chemfiles/chemfiles/blob/17a14fca75cfdd8754c8d00b52674bbadec83029/tests/trajectory.cpp#L261) which uses [molfiles](https://github.com/chemfiles/molfiles).

Steps to reproduce:
- use latest master (17a14fca)
- run `while :; do ctest --output-on-failure -j2 -R "^trajectory$"; done`
- observe failing tests (seems to have an occurrence of ~50% of the time)

Ref #422

**Comment by Luthaf** [comment]
Looks like one more reason to drop the molfiles code. 

I'm working on a rewrite of the DCD format, it seems to work pretty well. The main issue is finding test files for all possible variations of the format, some of which seems to be only created by software from the early 90s!

**Comment by Luthaf** [comment]
I don't think #422 is related, this was mostly windows code. From the error message, I would suspect some kind of issue with vmd plugin initialization (we might be initializing it mutliple time from different threads).
