### ISSUE TITLE
TPR file read error

### ISSUE THREAD

**Issue by SamTov** [chemfiles/chemfiles#472]
I get the following when reading a TPR file:

```sh
ChemfilesError: can not find a format associated with the '.tpr' extension
```

On the website it says that the tpr format is supported. It may be from an older version of gromacs but I don't think it is the wrong format.

**Comment by Luthaf** [comment]
https://github.com/chemfiles/chemfiles/pull/473 is the backport pull request

**Comment by SamTov** [comment]
Nice thank you!
