### ISSUE TITLE
the version of chemfiles does not match chemfiles-lib and chemfiles-python in conda-forge

### ISSUE THREAD

**Issue by z-gong** [chemfiles/chemfiles#477]
I'm trying to install `chemfiles 0.10.1` through `conda`
```
conda install -c conda-forge chemfiles=0.10.1
```

It turns out the latest version (0.10.3) gets installed
```
The following NEW packages will be INSTALLED:

  chemfiles          conda-forge/linux-64::chemfiles-0.10.1-ha770c72_0
  chemfiles-lib      conda-forge/linux-64::chemfiles-lib-0.10.3-h1cf7ff9_1
  chemfiles-python   conda-forge/linux-64::chemfiles-python-0.10.3-py310hfdc917e_1
```

**Comment by Luthaf** [comment]
Yes, the `chemfiles` package on conda depends on `chemfiles-lib >= 0.10` and `chemfiles-python >= 0.10`. If you want a specific version, you should set this version in your install command, i.e.

```
conda install -c conda-forge chemfiles-lib=0.10.1 chemfiles-python=0.10.1
```

**Comment by z-gong** [comment]
This is the intended behavior? I thought `chemfiles` is simply an alias of `chemfiles-lib` and `chemfiles-python`, which share the same version number.
