### ISSUE TITLE
case insensitive search for element(type) matching in PDB records

### ISSUE THREAD

**Issue by pgbarletta** [chemfiles/chemfiles#58]
In PDB ATOM records, elements are always in upper case. I haven't noted this before, since biological molecules are almost exclusively formed by CHONP atoms.
```
Atom::Atom(std::string name, std::string type):
    name_(std::move(name)), type_(std::move(type)) {
    auto periodic = PERIODIC_INFORMATION.find(type_);
    if (periodic != PERIODIC_INFORMATION.end()) {
        mass_ = periodic->second.mass;
    }
}
```

Maybe strings in [PERIODIC INFORMATION](https://github.com/pgbarletta/chemfiles/blob/master/include/chemfiles/periodic.hpp) should be lower case and a `std::tolower()` be applied to the query string before any search.

Please confirm and I'll apply this minor change myself.
Cheers!

**Comment by Luthaf** [comment]
I am a bit reluctant to change the strings in `PERIODIC_INFORMATION`, as they come from an external source of data (https://svn.code.sf.net/p/bodr/code/trunk/bodr/elements/elements.xml). At the same time, this information should not change often ^^

Maybe normalizing strings to an "Atom Case" before searching would be enough? `c` => `C`, `ZN` => `Zn`, ...

**Comment by pgbarletta** [comment]
Something like this 
```
  //! Set the atom type
    void set_type(std::string type) { 
      if (type.length() == 2) {
        type[0] = toupper(type[0]);
        type[1] = tolower(type[1]);
      }
      type_ = std::move(type); 
    }
```

- In `Atom.hpp` ?
- In the `Atom` constructor from `Atom.cpp` ?
- or `read_ATOM` from `PDB.cpp` ?

I was thinking of including it in `set_type` from `Atom.hpp` and moving the definition of the function to `Atom.cpp`, since the `Atom` constructor uses a nice intialization list to set the `type` variable. It also allows to construct `Atom` objects using the capitalization the user prefers, without overriding it. I don't know if this is a desired feature.

Again, sorry for taking so long for such a few lines of code.

**Comment by Luthaf** [comment]
>    In Atom.hpp ?
>    In the Atom constructor from Atom.cpp ?
>    or read_ATOM from PDB.cpp ?

I would prefer not to modify the types stored in `Atom`, but rather the matching function. Replacing all the lines like this in `Atom.cpp`

```cpp
auto periodic = PERIODIC_INFORMATION.find(type_);
```

With something like this:

```cpp
optional<ElementData> find_periodic_information(const std::string& type) {
    auto normalized_type = type;    
    if (normalized_type.length() == 2) {
        normalized_type[0] = toupper(normalized_type[0]);
        normalized_type[1] = tolower(normalized_type[1]);
    }
    // Do the search
};


// ...

auto periodic = find_periodic_information(type_);
```

With maybe some more clever tricks to prevent the copies. Using a custom comparison function may do the trick, we should try.
