### ISSUE TITLE
Unable to use after installed with conda

### ISSUE THREAD

**Issue by tonnamb** [chemfiles/chemfiles#70]
I did `conda install -c conda-forge chemfiles` into my python 2.7.13 environment and when try to `import chemfiles` I got this error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/envs/python2/lib/python2.7/site-packages/chemfiles/__init__.py", line 7, in <module>
    __version__ = get_c_library().chfl_version().decode("utf8")
  File "//anaconda/envs/python2/lib/python2.7/site-packages/chemfiles/find_chemfiles.py", line 36, in __call__
    self._cache = load_clib()
  File "//anaconda/envs/python2/lib/python2.7/site-packages/chemfiles/find_chemfiles.py", line 26, in load_clib
    "Could not find chemfiles library. Are you sure it's installed?"
ImportError: Could not find chemfiles library. Are you sure it's installed?
```

I traced it to the `cdll.LoadLibrary(libpath)` command in `find_chemfiles.py` and run it myself. I got this error thrown.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/envs/python2/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "//anaconda/envs/python2/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(//anaconda/envs/python2/lib/libchemfiles.dylib, 6): Library not loaded: @rpath/libmfhdf.0.dylib
  Referenced from: /anaconda/envs/python2/lib/libnetcdf.11.dylib
  Reason: image not found
```

I'm guessing that the dependency `libmfhdf.0.dylib` have not been installed properly.

**Comment by Luthaf** [comment]
Your guess seems right, and it looks like an issue with the way packages are declared in different channels.

Looking for `libmfhdf` error on google suggest to run `conda install hdf4`, does it solve the issue for you?

Also, what is the output of `conda config --get channels`?

**Comment by tonnamb** [comment]
After `conda install hdf4` the issue is solved! Thanks for replying.

Output of `conda config --get channels`:

--add channels 'defaults'   # lowest priority
--add channels 'anaconda-fusion'
--add channels 'MDAnalysis'   # highest priority

**Comment by Luthaf** [comment]
OK, great ! Maybe the users should add the conda-forge channel to the list, as they are distributing a copy of libnetcdf and hdf4.

Can you give me the OS you are using so that I can reproduce this?

**Comment by tonnamb** [comment]
Yep ! macOS Sierra Version 10.12.3

**Comment by Luthaf** [comment]
I can not reproduce this on a fresh install of miniconda in macOS. Maybe it has to do with anaconda or with the use of environments.

**Comment by tonnamb** [comment]
I see. That is possible as I have the full anaconda installed, and use a separate environment for python2.

**Comment by tonnamb** [comment]
Btw, `conda install -c conda-forge chemfiles` worked fine in my python3 environment (which is a default environment).
