### ISSUE TITLE
Selections within a selection

### ISSUE THREAD

**Issue by lscalfi** [chemfiles/chemfiles#73]
It is for now possible to select atoms, bonds, angles or dihedrals on the base of their components' name, type, coordinates...
It could be interesting to select atoms based on their bonded neighbours. We could create a selection inside a selection, for example:
"atoms: name O and bonded to {name H and x<5}"

**Comment by Luthaf** [comment]
Why is this needed exactly? Or putted an other way, why do we need this?

In cfiles, it is currently not possible to use selections with more than 2 atoms in rdf for examples, but nothing prevent us from allowing selections with 3 or 4 atoms, and then only using the first two. This would allow to write selections like: `three: name(#1) O and name(#2) H and name(#3) Si and bonded(#1, #3) and bonded(#1, #2)`.

Do you see other use case for this?

Adding a bonded selector would be nice in all the cases.
