### ISSUE TITLE
PDB format with more than 4 bonds per atom

### ISSUE THREAD

**Issue by lscalfi** [chemfiles/chemfiles#80]
If one atom has more than 4 bonds, chemfiles throws this error:
`PDB 'CONNECT' record can not handle more than 4 bonds, got 6 around atom 143.`

However, it should start a new CONECT line with the same ID number

**Comment by Luthaf** [comment]
Specifically, the PDB standard state that:

> If more than four fields are required for non hydrogen and non salt bridges, a second CONECT record with the same atom serial number in columns 7 -11 will be used.
