### ISSUE TITLE
Image mistake on the page of http://chemfiles.org/ 

### ISSUE THREAD

**Issue by noinil** [chemfiles/chemfiles#82]
Just a quick question: shouldn't "NetDCF" be "NetCDF" in the figure at the center of the homepage?
Possibly a typo?

<img width="368" alt="screen shot 2017-04-27 at 16 58 14" src="https://cloud.githubusercontent.com/assets/3176571/25473521/bfac0f42-2b6a-11e7-8d9f-77bf66d4b035.png">

**Comment by Luthaf** [comment]
Yes, this is a typo. Thanks for the report!

**Comment by Luthaf** [comment]
The fix is live at http://chemfiles.org/
