### ISSUE TITLE
PDB format: ATOM / HETATM selection

### ISSUE THREAD

**Issue by pgbarletta** [chemfiles/chemfiles#95]
Hi!
   I need to distinguish between atoms that came from ATOM records from those that came from HETATM records, and for what I have seen, chemfiles doesn't do this yet. 
My planed changes would be:

1_ Modify `Atom.hpp`: add a private member variable to the `Atom` class. Something like `bool hetatm_ = false`.

2_ Modify `Atom.cpp`: to print this bool. Eg, `const bool hetatm() const { return hetatm_; }`. 

3_ Modify `PDB.cpp`: from this:
```
case Record::ATOM:
case Record::HETATM:
         read_ATOM(frame, line);
         break;
```
to this:

```
case Record::ATOM:
         read_ATOM(frame, line);
         break;
case Record::HETATM:
         read_HETATM(frame, line);
         break;
```
or, ---since the difference between the 2 functinos (`read_ATOM` and `read_HETATM`) would only lie in the setting of the putative `hetatom_` variable---, something like this:

```
case Record::ATOM:
         read_xyz(frame, line, false);
         break;
case Record::HETATM:
         read_xyz(frame, line, true);
         break;
```
4_ Maybe add some test?

Hope I haven't overlooked anything.

**Comment by Luthaf** [comment]
Hey !

This looks like an interesting addition. Do you know other formats that also do this ATOM/HETATOM distinction ? Maybe mmCIF ? 

I am a bit worried about this that it is adding a public API function only for one format. Maybe it would be better as "additional data" in the frame, like a `is_hetatom = std::vector<bool>` in the frame (see #85 for the idea on storing additional data on the frame).

This would be more work, but if you need it, I can do the foundation work for this soon. Then you could use this additional data storage facility to store and then retrieve the information you need in PDB files ?

**Comment by pgbarletta** [comment]
Not that I know of. Every other format just reads "atoms". [mmCIF](http://mmcif.wwpdb.org/docs/pdb_to_pdbx_correspondences.html#ATOMP)  groups ATOMs and HETATMs in the Data Item `_atom_site`.

Right, it's a very specific use. How about this:

Since `Frame` objects are created for each frame and they all map to the same `Atom` object, I think this variable would correspond to the `Atom` class, since it would be a constant for each `Atom` object. I mean, it shouldn't change along a trajectory.

I'm thinking in a template class inside the `Atom` class, that is, a new member variable. It could be called just `info` and the user would access it by the `info()` method, which would return a reference to it. 
This `info` would only need to be Constructible and Assignable; and by just returning a reference to it, chemfiles doesn't need to know whether `info` turns out to be a `bool`, a `std::string` or a user-defined class. 
Later, the `read_ATOM` function from `PDB.cpp` would fill it with a `bool`, as any user would.

**Comment by Luthaf** [comment]
You are right about frame specific versus atom specific data.

The issue with having a template class member is that it would be restricted to C++, and I'd like to have the same functionality for all languages chemfiles is accessible from. Also, if I understand your proposal well, there would be no way to know what the `info` field is about if you don't know the file format it comes from, right ? The `bool` value could be `is_hetatom` or `is_anisotropic` or any other property, right ?

But I think we can solve the frame/atom data issue by using the same mechanism as #85, and having a properties map inside the atoms too.


The code could look something like this:
```cpp
class Value {
public:
    double as_double() const {
        if (kind_ == DOUBLE) {
            return double_;
        } else {
            throw Error()
        }
    }

    // Same with as_string, as_bool, ...

private:
    enum {
        BOOL,
        STRING,
        DOUBLE,
        VECTOR3D,
    } kind_;

    union {
        bool bool_,
        std::string string_,
        double double_,
        Vector3D vector3d_,
    };
};

using property_map = std::map<std::string, Value>;

class Frame {
    // ...

    const Value& get(const std::string& key) const;
    void set(std::string key, Value value);
private:
    property_map properties_;
}

class Atom {
    // ...

    const Value& get(const std::string& key) const;
    void set(std::string key, Value value);
private:
    property_map properties_;
}

// In PDB.cpp
atom.set("is_hetatom", Value(true));

// in your code
if (atom.get("is_hetatom").as_bool()) {
    // ...
}
```

This would be a more generic solution, handling the case of atom specific data. Also, it would remove the need of supporting `std::vector<Value>` in the properties map that would have been needed if everything was stored in the frame.

**Comment by pgbarletta** [comment]
You're right, this is the most generic you can get without getting too C++ specific. 
Let me know if I can do anything.

**Comment by Luthaf** [comment]
I can try to get the ground work for this working by the end of the week, and then you can work on the PDB side of the issue.

Or if you want, you can implement the `Property` class yourself, I'll be happy to help you going with this!

**Comment by pgbarletta** [comment]
I'll get on with the `Property` implementation on the PDB format by this weekend.

**Comment by Luthaf** [comment]
Ok!

**Comment by Luthaf** [comment]
Is this fixed now? Or is there anything left to do?

**Comment by pgbarletta** [comment]
Done!
